### ISSUE TITLE
Integrating with WAMPiS

### ISSUE THREAD

**Issue by JayEmmonds** [Comcast/weasel#2]
I'm trying to integrate this checker into the WAMPiS work flow on my department's shared license DB, but I can't seem to get the dependencies to download with my current account. I'm signed in as USER: Common14 Password: Tsacmoc1. Is there a step that's not documented? #XVLF#

**Comment by alficles** [comment]
I'm happy to help with the dependencies, since there are none outside the standard library for this tool, but the rest will depend on how your license DB works. I'm closing this, but you can reopen with appropriate details.

(Note: This is an open source project and all details posted here are public to the Internet. It's rarely a good idea to post passwords in such a forum.)
